import { collection,doc,getDoc,onSnapshot,orderBy,query,runTransaction,serverTimestamp,updateDoc,where,writeBatch,type Unsubscribe } from "firebase/firestore";
import { db } from "@/lib/firebase/client";
import type { AdminSubmission,AdminSubmissionStatus } from "@/types/admin";
import type { Place } from "@/types/place";
export function subscribeSubmissions(cb:(rows:AdminSubmission[])=>void):Unsubscribe{if(!db){cb([]);return()=>{}}return onSnapshot(query(collection(db,"place_submissions"),orderBy("createdAt","desc")),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}) as AdminSubmission)))}
export function subscribePlaces(cb:(rows:Place[])=>void):Unsubscribe{if(!db){cb([]);return()=>{}}return onSnapshot(query(collection(db,"places"),orderBy("createdAt","desc")),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}) as Place)))}
export function subscribeActivePlaces(cb:(rows:Place[])=>void):Unsubscribe{if(!db){cb([]);return()=>{}}return onSnapshot(query(collection(db,"places"),where("status","==","active"),orderBy("createdAt","desc")),s=>cb(s.docs.map(d=>({id:d.id,...d.data()}) as Place)))}
export function subscribeSubmission(id:string,cb:(row:AdminSubmission|null)=>void):Unsubscribe{if(!db){cb(null);return()=>{}}return onSnapshot(doc(db,"place_submissions",id),s=>cb(s.exists()?({id:s.id,...s.data()} as AdminSubmission):null))}
export async function markReviewing(id:string,uid:string){if(!db)return;const ref=doc(db,"place_submissions",id);await runTransaction(db,async tx=>{const snap=await tx.get(ref);if(snap.exists()&&snap.data().status==="pending")tx.update(ref,{status:"reviewing",reviewedBy:uid,reviewedAt:serverTimestamp()})})}
export async function saveAdminNotes(id:string,adminNotes:string){if(!db)throw new Error("Firebase belum dikonfigurasi");await updateDoc(doc(db,"place_submissions",id),{adminNotes})}
export async function updateReview(id:string,status:AdminSubmissionStatus,note:string,uid:string){if(!db)throw new Error("Firebase belum dikonfigurasi");const patch:Record<string,unknown>={status,reviewedBy:uid,reviewedAt:serverTimestamp()};if(status==="revision_required")patch.revisionNote=note;if(status==="rejected")patch.rejectReason=note;const subRef=doc(db,"place_submissions",id);const snap=await getDoc(subRef);const batch=writeBatch(db);batch.update(subRef,patch);if(snap.exists()){const s=snap.data() as AdminSubmission;const safe:Record<string,unknown>={submissionCode:s.submissionCode,name:s.name,status,updatedAt:serverTimestamp()};if(status==="revision_required")safe.revisionNote=note;if(status==="rejected")safe.rejectReason=note;batch.set(doc(db!,"submission_status_public",s.submissionCode),safe,{merge:true})}await batch.commit()}
function slugify(v:string){return v.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
export async function approveSubmission(id:string,uid:string):Promise<string>{if(!db)throw new Error("Firebase belum dikonfigurasi");const subRef=doc(db,"place_submissions",id);return runTransaction(db,async tx=>{const snap=await tx.get(subRef);if(!snap.exists())throw new Error("Submission tidak ditemukan");const s=snap.data() as AdminSubmission;if(s.publishedPlaceId)return s.publishedPlaceId;if(s.status==="approved")throw new Error("Submission ini sudah dipublikasikan.");if(!s.name||!s.categoryId||s.latitude==null||s.longitude==null||!s.coverImage)throw new Error("Data submission belum lengkap.");const placeRef=doc(collection(db!,"places"));const privateKeys=new Set(["id","submitterName","submitterWhatsapp","adminNotes","revisionNote","rejectReason","reviewedBy","reviewedAt","approvedBy","approvedAt","publishedPlaceId","status","submissionCode","createdAt"]);const publicData=Object.fromEntries(Object.entries(s).filter(([k])=>!privateKeys.has(k)));tx.set(placeRef,{...publicData,halalStatus:s.halalStatus==="non-halal"?"non_halal":s.halalStatus,slug:`${slugify(s.name)}-${placeRef.id.slice(0,5)}`,status:"active",verificationStatus:"verified",ownershipStatus:"unclaimed",plan:"free",featured:false,featuredUntil:null,rating:0,totalReviews:0,views:0,whatsappClicks:0,directionClicks:0,favoriteCount:0,sourceSubmissionId:id,submissionCode:s.submissionCode,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});tx.set(doc(db!,"submission_status_public",s.submissionCode),{submissionCode:s.submissionCode,name:s.name,status:"approved",publishedPlaceId:placeRef.id,updatedAt:serverTimestamp()});tx.update(subRef,{status:"approved",approvedBy:uid,approvedAt:serverTimestamp(),reviewedBy:uid,reviewedAt:serverTimestamp(),publishedPlaceId:placeRef.id});return placeRef.id})}
export async function togglePlaceStatus(id:string,status:"active"|"inactive"){if(!db)throw new Error("Firebase belum dikonfigurasi");await updateDoc(doc(db,"places",id),{status,updatedAt:serverTimestamp()})}