"use client";
import dynamic from "next/dynamic";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,ArrowRight,LocateFixed,Store,CheckCircle2,ShieldCheck } from "lucide-react";
import { useRouter } from "next/navigation";
import { categories,categoryById } from "@/data/categories";
import { cirebonRegions } from "@/data/regions";
import { trackEvent } from "@/lib/analytics";
import { normalizeIndonesianPhone } from "@/lib/whatsapp";
import { submitPlace } from "@/lib/submission";
import { validateSubmissionStep } from "@/lib/validation";
import type { FieldErrors,PlaceSubmissionDraft } from "@/types/placeSubmission";
import type { SubmissionProductDraft } from "@/types/menuItem";
import type { OpeningHours } from "@/types/place";
import { Stepper } from "./Stepper";
import { OpeningHoursEditor } from "./OpeningHoursEditor";
import { PhotoUploader } from "./PhotoUploader";
import { ProductStep } from "./ProductStep";
const LocationPicker=dynamic(()=>import("./LocationPicker"),{ssr:false,loading:()=> <div className="add-map-loading">Memuat peta…</div>});
const DRAFT_KEY="jajan-cirebon:add-place-draft:v1";
const days=["monday","tuesday","wednesday","thursday","friday","saturday","sunday"] as const;
const initialHours=Object.fromEntries(days.map(day=>[day,{open:"08:00",close:"21:00",closed:false}])) as OpeningHours;
const initial:PlaceSubmissionDraft={name:"",categoryId:"",description:"",priceMin:"",priceMax:"",serviceTypes:[],halalStatus:"unknown",province:"Jawa Barat",regencyType:"city",regency:"Kota Cirebon",district:"",village:"",address:"",latitude:null,longitude:null,whatsapp:"",phone:"",instagram:"",tiktok:"",facebook:"",submitterName:"",submitterWhatsapp:"",openingHours:initialHours};
const serviceOptions=["Makan di tempat","Bawa pulang","Pesan antar","Pre-order"];
const stepTitles=["Informasi usaha","Lokasi usaha","Kontak","Jam operasional","Foto usaha","Produk / Menu","Tinjau pendaftaran"];
function FieldError({name,errors}:{name:string;errors:FieldErrors}){return errors[name]?<p className="field-error">{errors[name]}</p>:null}
function Label({children,optional}:{children:React.ReactNode;optional?:boolean}){return <span className="add-label">{children}{optional?<small>Opsional</small>:<em>*</em>}</span>}
export default function AddPlaceWizard(){const router=useRouter();const [step,setStep]=useState(0);const [data,setData]=useState(initial);const [errors,setErrors]=useState<FieldErrors>({});const [cover,setCover]=useState<File|null>(null);const [gallery,setGallery]=useState<File[]>([]);const [products,setProducts]=useState<SubmissionProductDraft[]>([]);const [saved,setSaved]=useState<PlaceSubmissionDraft|null>(null);const [draftChoice,setDraftChoice]=useState(false);const [toast,setToast]=useState("");const [submitting,setSubmitting]=useState(false);
 useEffect(()=>{trackEvent("add_place_start");const timer=window.setTimeout(()=>{try{const raw=localStorage.getItem(DRAFT_KEY);if(raw)setSaved(JSON.parse(raw) as PlaceSubmissionDraft)}catch{localStorage.removeItem(DRAFT_KEY)}setDraftChoice(true)},0);return()=>window.clearTimeout(timer)},[]);
 useEffect(()=>{if(!draftChoice||(!data.name&&!data.description&&!data.address&&!data.whatsapp))return;const timer=window.setTimeout(()=>localStorage.setItem(DRAFT_KEY,JSON.stringify(data)),250);return()=>window.clearTimeout(timer)},[data,draftChoice]);
 const region=useMemo(()=>cirebonRegions.find(r=>r.name===data.regency)??cirebonRegions[0],[data.regency]);const district=region.districts.find(d=>d.name===data.district);
 const update=<K extends keyof PlaceSubmissionDraft>(key:K,value:PlaceSubmissionDraft[K])=>{setData(v=>({...v,[key]:value}));setErrors(v=>{const n={...v};delete n[String(key)];return n})};
 const next=()=>{const e=validateSubmissionStep(step,data,Boolean(cover),products.length);if(Object.keys(e).length){setErrors(e);trackEvent("add_place_error",`step-${step+1}`);window.scrollTo({top:0,behavior:"smooth"});return}trackEvent("add_place_step_completed",`step-${step+1}`);setErrors({});setStep(v=>Math.min(6,v+1));window.scrollTo({top:0,behavior:"smooth"})};
 const back=()=>{if(step===0)return;setErrors({});setStep(v=>v-1);window.scrollTo({top:0,behavior:"smooth"})};
 const pickLocation=(lat:number,lng:number)=>{update("latitude",Number(lat.toFixed(6)));update("longitude",Number(lng.toFixed(6)));trackEvent("add_place_location_selected")};
 const locate=()=>{if(!navigator.geolocation){setToast("Geolokasi tidak didukung perangkat ini.");return}navigator.geolocation.getCurrentPosition(p=>{pickLocation(p.coords.latitude,p.coords.longitude);setToast("Lokasi perangkat berhasil digunakan.")},()=>setToast("Izin lokasi ditolak. Pilih titik secara manual pada peta."),{enableHighAccuracy:true,timeout:10000})};
 const submit=async()=>{setSubmitting(true);trackEvent("add_place_submit");try{const result=await submitPlace(data,cover,gallery,products);localStorage.removeItem(DRAFT_KEY);trackEvent("add_place_success");router.push(`/add-place/success?ref=${encodeURIComponent(result.reference)}`)}catch(error){trackEvent("add_place_error","submit");setToast(error instanceof Error?error.message:"Pendaftaran belum terkirim. Silakan coba lagi.");setSubmitting(false)}};
 const input=(key:keyof PlaceSubmissionDraft,label:string,props:React.InputHTMLAttributes<HTMLInputElement>={})=><label className="add-field"><Label optional={Boolean(props["aria-label"])}>{label}</Label><input value={String(data[key]??"")} onChange={e=>update(key,e.target.value as never)} {...props}/><FieldError name={String(key)} errors={errors}/></label>;
 return <main className="add-page"><header className="add-header"><Link href="/" aria-label="Kembali ke peta"><ArrowLeft size={19}/></Link><div><strong>Daftarkan UMKM</strong><span>Gratis untuk ditemukan</span></div><Store size={20}/></header><div className="add-container"><Stepper current={step}/><section className="add-card"><div className="add-card-heading"><span>Langkah {step+1} dari 7</span><h1>{stepTitles[step]}</h1><p>{step===6?"Pastikan informasi sudah benar sebelum dikirim.":step===5?"Tambahkan produk atau menu yang ingin ditampilkan di halaman usaha Anda.":"Lengkapi informasi berikut agar usaha mudah ditemukan."}</p></div>{toast&&<div className="add-toast" role="status">{toast}<button onClick={()=>setToast("")} aria-label="Tutup">×</button></div>}
 {step===0&&<div className="add-form-grid">{input("name","Nama usaha",{placeholder:"Contoh: Empal Gentong Mang Darma"})}<fieldset className="add-field full"><Label>Kategori</Label><div className="choice-grid">{categories.map(c=><label className={data.categoryId===c.id?"selected":""} key={c.id}><input type="radio" name="category" checked={data.categoryId===c.id} onChange={()=>update("categoryId",c.id)}/><span>{c.icon}</span>{c.name}</label>)}</div><FieldError name="categoryId" errors={errors}/></fieldset><label className="add-field full"><Label>Deskripsi singkat</Label><textarea maxLength={500} rows={5} value={data.description} onChange={e=>update("description",e.target.value)} placeholder="Ceritakan menu unggulan dan karakter usaha…"/><small className="counter">{data.description.length}/500</small><FieldError name="description" errors={errors}/></label>{input("priceMin","Harga mulai",{type:"number",min:0,placeholder:"10000"})}{input("priceMax","Harga maksimum",{type:"number",min:0,placeholder:"50000","aria-label":"Opsional"})}<fieldset className="add-field full"><Label>Layanan</Label><div className="check-grid">{serviceOptions.map(v=><label key={v}><input type="checkbox" checked={data.serviceTypes.includes(v)} onChange={e=>update("serviceTypes",e.target.checked?[...data.serviceTypes,v]:data.serviceTypes.filter(x=>x!==v))}/>{v}</label>)}</div></fieldset><fieldset className="add-field full"><Label>Status halal</Label><div className="radio-row">{[["halal","Halal"],["non-halal","Non-halal"],["unknown","Belum dicantumkan"]].map(([v,l])=><label key={v}><input type="radio" checked={data.halalStatus===v} onChange={()=>update("halalStatus",v as PlaceSubmissionDraft["halalStatus"])}/>{l}</label>)}</div></fieldset></div>}
 {step===1&&<div className="add-form-grid"><label className="add-field"><Label>Provinsi</Label><input disabled value="Jawa Barat"/></label><label className="add-field"><Label>Kota/Kabupaten</Label><select value={data.regency} onChange={e=>{const r=cirebonRegions.find(x=>x.name===e.target.value)!;setData(v=>({...v,regency:r.name,regencyType:r.type,district:"",village:""}))}}>{cirebonRegions.map(r=><option key={r.name}>{r.name}</option>)}</select></label><label className="add-field"><Label>Kecamatan</Label><select value={data.district} onChange={e=>{update("district",e.target.value);update("village","")}}><option value="">Pilih kecamatan</option>{region.districts.map(d=><option key={d.name}>{d.name}</option>)}</select><FieldError name="district" errors={errors}/></label><label className="add-field"><Label>Kelurahan/Desa</Label><select disabled={!district} value={data.village} onChange={e=>update("village",e.target.value)}><option value="">Pilih kelurahan/desa</option>{district?.villages.map(v=><option key={v}>{v}</option>)}</select><FieldError name="village" errors={errors}/></label><label className="add-field full"><Label>Alamat lengkap</Label><textarea rows={3} value={data.address} onChange={e=>update("address",e.target.value)} placeholder="Nama jalan, nomor, patokan…"/><FieldError name="address" errors={errors}/></label><div className="add-field full"><div className="location-head"><Label>Titik lokasi</Label><button type="button" onClick={locate}><LocateFixed size={15}/> Gunakan lokasi saya</button></div><LocationPicker latitude={data.latitude} longitude={data.longitude} onChange={pickLocation}/><p className="map-help">Klik peta atau geser pin. Koordinat: {data.latitude??"—"}, {data.longitude??"—"}</p><FieldError name="location" errors={errors}/></div></div>}
 {step===2&&<div className="add-form-grid">{input("whatsapp","WhatsApp usaha",{inputMode:"tel",placeholder:"08xxxxxxxxxx"})}{input("phone","Telepon",{inputMode:"tel",placeholder:"Opsional","aria-label":"Opsional"})}{input("instagram","Instagram",{placeholder:"@namausaha","aria-label":"Opsional"})}{input("tiktok","TikTok",{placeholder:"@namausaha","aria-label":"Opsional"})}{input("facebook","Facebook",{placeholder:"Nama halaman","aria-label":"Opsional"})}<div className="privacy-note full"><ShieldCheck size={18}/><span><strong>Data pengirim bersifat privat</strong>Hanya dipakai tim untuk verifikasi pendaftaran.</span></div>{input("submitterName","Nama pengirim",{placeholder:"Nama lengkap"})}{input("submitterWhatsapp","WhatsApp pengirim",{inputMode:"tel",placeholder:"08xxxxxxxxxx"})}</div>}
 {step===3&&<OpeningHoursEditor value={data.openingHours} onChange={v=>update("openingHours",v)}/>} {step===4&&<PhotoUploader cover={cover} gallery={gallery} onCover={setCover} onGallery={setGallery} error={errors.coverImage} onError={v=>setErrors(e=>({...e,coverImage:v}))}/>} {step===5&&<ProductStep products={products} onChange={setProducts} error={errors.products} onError={message=>setErrors(current=>({...current,products:message}))}/>} {step===6&&<div className="review-list"><Review title="Usaha" onEdit={()=>setStep(0)}><strong>{data.name}</strong><span>{categoryById[data.categoryId]?.name} · {data.description}</span><span>Rp {data.priceMin||"—"} – Rp {data.priceMax||"—"}</span></Review><Review title="Lokasi" onEdit={()=>setStep(1)}><strong>{data.village}, {data.district}</strong><span>{data.address}, {data.regency}</span><span>{data.latitude}, {data.longitude}</span></Review><Review title="Kontak" onEdit={()=>setStep(2)}><strong>WhatsApp +{normalizeIndonesianPhone(data.whatsapp)}</strong><span>{data.instagram||"Tanpa Instagram"}</span></Review><Review title="Jam operasional" onEdit={()=>setStep(3)}><span>Jadwal 7 hari sudah diatur</span></Review><Review title="Foto" onEdit={()=>setStep(4)}><strong>1 foto utama · {gallery.length} foto galeri</strong></Review><Review title="Produk" onEdit={()=>setStep(5)}><strong>{products.length} produk</strong><span>{products.map(product=>product.name).join(", ")}</span></Review><div className="pending-note"><CheckCircle2 size={19}/><span><strong>Akan ditinjau sebelum tayang</strong>Pendaftaran berstatus pending, unverified, unclaimed, paket free, dan belum tampil di peta publik.</span></div></div>}
 </section><footer className="add-actions">{step>0?<button className="add-back" type="button" onClick={back}><ArrowLeft size={16}/> Kembali</button>:<Link className="add-back" href="/"><ArrowLeft size={16}/> Batal</Link>} {step<6?<button className="add-next" type="button" onClick={next}>Lanjut <ArrowRight size={16}/></button>:<button className="add-next" disabled={submitting} type="button" onClick={()=>void submit()}>{submitting?"Mengirim…":"Kirim pendaftaran"}</button>}</footer></div>
 {saved&&draftChoice&&<div className="draft-overlay"><div className="draft-modal"><Store size={25}/><h2>Lanjutkan draft?</h2><p>Ada pendaftaran yang belum selesai di perangkat ini.</p><button className="add-next" onClick={()=>{setData(saved);setSaved(null)}}>Lanjutkan draft</button><button className="add-back" onClick={()=>{localStorage.removeItem(DRAFT_KEY);setData(initial);setSaved(null)}}>Mulai baru</button></div></div>}</main>}
function Review({title,onEdit,children}:{title:string;onEdit:()=>void;children:React.ReactNode}){return <article className="review-card"><div><h2>{title}</h2><button type="button" onClick={onEdit}>Edit</button></div>{children}</article>}