"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { BarChart3,ClipboardList,LayoutDashboard,LogOut,MapPinned,Settings,Shapes,Store } from "lucide-react";
import { firebaseConfigured } from "@/lib/firebase/client";
import { useAdminAuth } from "./AdminAuthProvider";
const nav=[{href:"/admin",label:"Dashboard",icon:LayoutDashboard},{href:"/admin/submissions",label:"Pendaftaran UMKM",icon:ClipboardList},{href:"/admin/places",label:"Data UMKM",icon:MapPinned},{href:"#",label:"Kategori",icon:Shapes,disabled:true},{href:"#",label:"Analytics",icon:BarChart3,disabled:true},{href:"#",label:"Pengaturan",icon:Settings,disabled:true}];
export function AdminShell({children}:{children:React.ReactNode}){const path=usePathname();const {admin,loading,error,login,logout}=useAdminAuth();if(!firebaseConfigured)return <AdminSetup/>;if(loading)return <main className="admin-gate">Memverifikasi akses admin…</main>;if(!admin)return <AdminLogin error={error} onLogin={login}/>;return <div className="admin-shell"><aside className="admin-sidebar"><Link className="admin-brand" href="/admin"><span><Store size={18}/></span><div><strong>Jajan Cirebon</strong><small>Admin Operasional</small></div></Link><nav>{nav.map(item=>{const Icon=item.icon;const active=item.href==="/admin"?path===item.href:path.startsWith(item.href);return item.disabled?<span className="disabled" key={item.label}><Icon size={16}/>{item.label}<small>Segera</small></span>:<Link className={active?"active":""} href={item.href} key={item.label}><Icon size={16}/>{item.label}</Link>})}</nav><button className="admin-logout" onClick={()=>void logout()}><LogOut size={16}/> Keluar</button></aside><div className="admin-main"><header className="admin-topbar"><div><strong>Admin Dashboard</strong><small>{admin.email} · {admin.role}</small></div></header>{children}</div></div>}
function AdminSetup(){return <main className="admin-gate"><div><Store size={28}/><h1>Firebase belum dikonfigurasi</h1><p>Tambahkan environment `NEXT_PUBLIC_FIREBASE_*` untuk mengaktifkan Authentication dan Firestore. Akses admin tidak dibuka dalam mode fallback.</p><Link href="/">Kembali ke aplikasi publik</Link></div></main>}
function AdminLogin({error,onLogin}:{error:string;onLogin:(e:string,p:string)=>Promise<void>}){return <main className="admin-gate"><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void onLogin(String(f.get("email")),String(f.get("password"))).catch(()=>{})}}><Store size={27}/><h1>Login Admin</h1><p>Gunakan akun Firebase yang terdaftar aktif pada collection admins.</p><label>Email<input name="email" type="email" required/></label><label>Password<input name="password" type="password" required/></label>{error&&<p className="admin-error">{error}</p>}<button type="submit">Masuk</button><Link href="/">Kembali ke aplikasi publik</Link></form></main>}