"use client";
import{createContext,useContext,useEffect,useState}from"react";
import{onAuthStateChanged,signInWithEmailAndPassword,signOut,type User}from"firebase/auth";
import{auth,firebaseConfigured}from"@/lib/firebase/client";
import{getAdminProfile}from"@/lib/adminAuth";
import type{AdminProfile}from"@/types/admin";
interface State{user:User|null;admin:AdminProfile|null;adminProfile:AdminProfile|null;isAdmin:boolean;loading:boolean;error:string;login:(email:string,password:string)=>Promise<void>;logout:()=>Promise<void>}
const Context=createContext<State|null>(null);
const deniedMessage="Akses tidak diizinkan. Pastikan akun terdaftar sebagai admin aktif.";
export function AdminAuthProvider({children}:{children:React.ReactNode}){const[user,setUser]=useState<User|null>(null);const[admin,setAdmin]=useState<AdminProfile|null>(null);const[loading,setLoading]=useState(firebaseConfigured);const[error,setError]=useState("");useEffect(()=>{if(!auth)return;const firebaseAuth=auth;return onAuthStateChanged(firebaseAuth,async current=>{setLoading(true);if(!current){setUser(null);setAdmin(null);setError("");setLoading(false);return}try{const profile=await getAdminProfile(current.uid);if(!profile)throw new Error(deniedMessage);setUser(current);setAdmin(profile);setError("")}catch{setUser(null);setAdmin(null);setError(deniedMessage);if(firebaseAuth.currentUser)await signOut(firebaseAuth).catch(()=>undefined)}finally{setLoading(false)}})},[]);const login=async(email:string,password:string)=>{if(!auth)throw new Error("Firebase belum dikonfigurasi.");setLoading(true);setError("");try{const result=await signInWithEmailAndPassword(auth,email,password);const profile=await getAdminProfile(result.user.uid);if(!profile){await signOut(auth);throw new Error(deniedMessage)}setUser(result.user);setAdmin(profile)}catch(e){const permissionDenied=e instanceof Error&&(e.message.includes("permission")||e.message===deniedMessage);const message=permissionDenied?deniedMessage:"Email atau password tidak valid.";setError(message);throw new Error(message)}finally{setLoading(false)}};const logout=async()=>{if(auth)await signOut(auth)};return <Context.Provider value={{user,admin,adminProfile:admin,isAdmin:Boolean(admin),loading,error,login,logout}}>{children}</Context.Provider>}
export function useAdminAuth(){const value=useContext(Context);if(!value)throw new Error("AdminAuthProvider tidak tersedia");return value}