"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { Search } from "lucide-react";
import { subscribeSubmissions } from "@/lib/adminData";
import { categoryById } from "@/data/categories";
import type { AdminSubmission,AdminSubmissionStatus } from "@/types/admin";
export const statusLabels:Record<AdminSubmissionStatus,string>={pending:"Pending",reviewing:"Reviewing",revision_required:"Perlu Revisi",approved:"Approved",rejected:"Rejected"};
export function SubmissionList({limit}:{limit?:number}){const [rows,setRows]=useState<AdminSubmission[]>([]);const [search,setSearch]=useState("");const [status,setStatus]=useState<"all"|AdminSubmissionStatus>("all");const [region,setRegion]=useState("all");useEffect(()=>subscribeSubmissions(setRows),[]);const counts=useMemo(()=>Object.fromEntries(Object.keys(statusLabels).map(s=>[s,rows.filter(r=>r.status===s).length])),[rows]);const filtered=useMemo(()=>rows.filter(r=>{const q=`${r.submissionCode} ${r.name} ${r.submitterName} ${r.submitterWhatsapp} ${r.district} ${r.regency}`.toLowerCase();return q.includes(search.toLowerCase())&&(status==="all"||r.status===status)&&(region==="all"||r.regency===region)}).slice(0,limit),[rows,search,status,region,limit]);return <div><div className="admin-status-grid">{(Object.keys(statusLabels) as AdminSubmissionStatus[]).map(s=><button className={status===s?"active":""} key={s} onClick={()=>setStatus(status===s?"all":s)}><span>{statusLabels[s]}</span><strong>{counts[s]||0}</strong></button>)}</div>{!limit&&<div className="admin-filters"><label><Search size={15}/><input placeholder="Cari kode, nama UMKM, atau pengaju..." value={search} onChange={e=>setSearch(e.target.value)}/></label><select value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Semua status</option>{Object.entries(statusLabels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select><select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">Semua wilayah</option><option>Kota Cirebon</option><option>Kabupaten Cirebon</option></select></div>}<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Kode</th><th>Nama UMKM</th><th>Kategori</th><th>Wilayah</th><th>Pengaju</th><th>Tanggal</th><th>Status</th><th>Aksi</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td data-label="Kode">{r.submissionCode}</td><td data-label="Nama"><strong>{r.name}</strong></td><td data-label="Kategori">{categoryById[r.categoryId]?.name||r.categoryId}</td><td data-label="Wilayah">{r.district}<small>{r.regency}</small></td><td data-label="Pengaju">{r.submitterName}</td><td data-label="Tanggal">{formatDate(r.createdAt)}</td><td data-label="Status"><span className={`status-badge ${r.status}`}>{statusLabels[r.status]}</span></td><td><Link href={`/admin/submissions/${r.id}`}>Lihat</Link></td></tr>)}</tbody></table>{!filtered.length&&<div className="admin-empty">Belum ada submission yang sesuai.</div>}</div></div>}
export function formatDate(value:unknown){if(!value)return "—";const d=typeof value==="object"&&value!==null&&"toDate" in value?(value as {toDate:()=>Date}).toDate():new Date(String(value));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("id-ID").format(d)}